package org.example.rpcprotocol;

public enum RequestType {
    LOGIN, LOGOUT, FIND_ORGANIZING, NUMBER_OF_CHILDREN_FOR_SAMPLE, FIND_ALL_SAMPLES, FIND_SAMPLE, REGISTER_CHILD, FIND_CHILD, SAVE_CHILD, NEW, LIST_CHILDREN_FOR_SAMPLE
}
