package org.example.rpcprotocol;

public enum ResponseType {
ORGANIZING_LOGGED_IN,OK, PARTICIPANTS_REGISTERED, ORGANIZING_LOGGED_OUT, FIND_ALL_SAMPLES, FIND_ORGANIZING, FIND_SAMPLE, LIST_CHILDREN, FIND_CHILD, SAVE_CHILD, LOGIN, REGISTER_CHILD, NEW, ERROR
}
